version: '4.4.2'

services:
  nginx:
    image: nginx
    volumes:
      - ./production/nginx:/etc/nginx/conf.d
      - ./front-end:/var/www/front-end
      - ./certs/certs:/certs
    ports:
      - "80:80" 
      - "443:443"
  
  back-end:
    build: .
    volumes:
      - ./production/.env:/api-flask/.env
    expose:
      - "5000"

  redis:
    image: redis:alpine
    container_name: redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    env_file:
      - .env

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
    - "8081:8081"